[package]
name = "apiplant-driver-sqlx"
version = "0.1.0"
authors = ["Federico Rampazzo <frampone@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
apiplant-server-lib = { path = "../apiplant-server-lib" }
sqlx = "0.3.2"